dist: trusty
sudo: required
language: node_js
addons:
  sonarcloud:
    projectKey: "eduardo-website"
    organization: "eduardoac-github"
    token:
      secure: SONAR_TOKEN
jdk:
  - oraclejdk8
node_js:
  - 8
cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
script:
  - npm test
  - sonar-scanner
