name = "subscription-handler"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

[env.production]
name = "subscription-handler"
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "EMAIL_KV"
id = "0c3bb7d68a3b4959a2b3482a92cb766c"
preview_id = "015cde3a803a40a78cd525d6a7ed0d27"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "EMAIL_KV"
id = "0c3bb7d68a3b4959a2b3482a92cb766c"
preview_id = "015cde3a803a40a78cd525d6a7ed0d27"

[observability.logs]
enabled = true

# Environment variables (these will be set via wrangler secret)
# RESEND_API_KEY
# FROM_EMAIL
# TO_EMAIL
# ALLOWED_ORIGIN

# [vars]
# RESEND_API_KEY = "example.com"
# FROM_EMAIL = "example_user"
# TO_EMAIL = ""
# ALLOWED_ORIGIN = ""