name = "subscription-handler"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

[env.production]
name = "subscription-handler"
vars = { ENVIRONMENT = "production" }

[observability.logs]
enabled = true

# Environment variables (these will be set via wrangler secret)
# RESEND_API_KEY
# FROM_EMAIL
# TO_EMAIL
# ALLOWED_ORIGIN
# AUDIENCE_ID

# [vars]
# RESEND_API_KEY = "example.com"
# FROM_EMAIL = "example_user"
# TO_EMAIL = ""
# ALLOWED_ORIGIN = ""
