name = "subscription-handler"
main = "src/index.tsx"
compatibility_date = "2024-01-01"

# KV namespace for rate limiting
[[kv_namespaces]]
binding = "EMAIL_KV"
id = "email_kv_namespace"
preview_id = "015cde3a803a40a78cd525d6a7ed0d27"

# Environment variables (these will be set via wrangler secret)
# RESEND_API_KEY
# FROM_EMAIL
# TO_EMAIL
# ALLOWED_ORIGIN 