name: Visual Regression Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install
      
    - name: Build the application
      run: npm run build
      
    - name: Start the application
      run: npm start &
      
    - name: Wait for application to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
        
    - name: Run visual regression tests
      run: |
        # Update the baseUrl in lostpixel.config.ts for CI
        sed -i 's|http://localhost:3001|http://localhost:3000|g' lostpixel.config.ts
        npm run lost-pixel
        
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lost-pixel-screenshots
        path: .lostpixel/
        retention-days: 7 